travis:
  secure:
    BINSTAR_TOKEN: Q3EUYNFAIj9ouRz4JuzGDwz8yVSfJbtlMhuGP8PszE6ei7vxzXR6o1D/k8/uuO6z5JE1XiNnkzuJKJsMvaD+zwGMTwyfbhKj1XY9oBF/EXhhjPPMcFQlcFseGC9bEb74O0QTuCPCUhZo8IxM69sgCbGAs4oXg/r6cS+gRG4lIyOQmqPfDNlfrrdUaBLttJ+vw4USAl2cXHaH7IbzG4qNyzqm9pmer00xXhvNJnnHtDNDcvVZvT6EfpIdpJA9ICxzjTJuz+i0STavkEZa562bInWMi3OZQmFooce1YdVvmItp2OvMW+HOI2h+6CwJWm3RQnnG7aNqCapw9Bh4Veklv2i16UEh8mR6sVch09M+S27o+ZslOGAsXtNlA0ZWL4Oue995jkQVBkZbMN5cg2a8f9/9nn1KP2zQhzADyxTfXKQ+9Ct6GdVg099A99o0Ge0VxQd09ADcxaCvSUaN7IbsblyIDcuxVsSJHs1EmhZxDSubzEUgCmB/T5E/p+4Jg4UQ+aEPHZdQUKori4hxotWi5erqwfADMAw/ldgIojpQHjMjdfcx5jJSg/rb7OczyLk9iXveHhqvuCSlfSZNFsbZlzLVZ2n3cnmjhujHEWG9BLAs3ksEItB0hUgMPuCGlr3BTpmwsMYg5wKywFrCFk3Dd7VuucBFKDZz6Hjx25dijbU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
