travis:
  secure:
    BINSTAR_TOKEN: pEjJaf0WFehiGR/U3AlZFbK6V/vr3UwwpTwmqi09RJ640CJZtj6eDY2e72HxTzvciweDz71xTEJim89QE6vKVn1HjBWY5wc1FSSCOOAntOkQr9ImPeZ6r1vOM2XRMThmebpz1UGnctBmSkWCD58oWQ6cPlDE5nKbXb7ZQqIYpuqy31ofyKwlWxq7e6qLwYio0LC86E5OWfOhm8XHia1LXsN1cRdmIxUUFAiCHu8YujVd5UMWZwCvI0d8+mUKWBiVcJILhkqCCV9APtkN15Pw2nxAH6qvOnVSk7Kp1rbiuP5t0nsQ7cmQ5DElNHBvMwdRtFh8sLFbPrRLnzFrhDP4RioU+j3tsYIHBG6+SpQXaZWRrMMRBp4r2RZko9L5h+iysjRrFA9/w2MM/f46GQLr791qBqnFKbP+sFc34B+kBymSIO4v7qVUmmlNswlYzY9BY4xDvD84mts8RHVwiwZIvmcH7YVshCut4kzWLBI/vCw67QBzm1hf6k1xP+f0vfYZrIop/H5T9WfFWLBRKsc0nHCbqKQmHPY+CHizQ3DENYf54YWl0wHqm8El3eJp+SQt+mWLFPNhCu9+953KtcMsEqZGBf5+DCMag+I+i/MlGCUlPKmjVBqbCvMMx1SBi8v4fj8BV+GDUkxE8O2wiE0pgU7KQ3yVuFf8alBk0JDZOhA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
