travis:
  secure:
    BINSTAR_TOKEN: R9BCi97YxFWYgEWZvmIdWCTXPXXwGWZoK+ageS0uUIDfQFLZPb2ivJRMnvZbUajHZ3tdbI2IQ7fGsS+5Qml8SHHgffNNce3z5MwCIs34fN05aLOqtlqUWPkKtUPeoACHQifGEVd3dOBNK1FP0fXy7HeqWUaZLzkMp0I8ASfc9snS4DvDCB7NTk9KqhiNfaPSNnIcJjztgk3rdopOlLvDsfyfVy/R878P1rXz/24oVKEUMqcZ4bcfzwXJuGUPFNwM2JVh39lyHTCDWM884OOAffGwgoUM9HV9BgsloMmLPplxZQlbxZCuKSvIH3Eo8y2NQWL2PsamTXmY5NNLDfEZXk1bAhqbAMr6REaN2NeoER9P7+PPzPmxgMOCywKBNYfiTXX6AagNiejmqJ8x50QCmSuitwBEgDpWl4uBr1u9I2wZEjWSFSFAU83dkse4bHwnxYFMvEZn944kCUI0aVBnLVALHboX4tdz+jBfX0MG+jnW4bEM9ZmTCQlxKiGWaMRdAfuM6Bs9fTJyQ89wUwkP2gKB996pb7lR9lXYaYxjPoa9N075l7lr9yGmeTX3VhxnNew1T+l0AhtqcIzsZ8iDjFD6zAA1Rx4P8PasRz3E4HQWW8veybHqPFfJ4vgDZq2qwQrnQYP3tMe/Acg4ppjjper0gHOC8uGXOfK19iYA9pA=
appveyor:
  secure:
    BINSTAR_TOKEN: KDvUkPrcdKmV2MxakkyQlrLA0rE/6WSuXxD42UezzZjCB0TRqnnOeebSW03/SnFP
